DEFAULTS = {
    "window_title": "SwissTopo STL Converter",
    "window_geometry": "1200x1000",
    "model_name": "terrain",
    "csv_path": "",
    "download_workers": "10",
    "download_all_csv": True,
    "convert_workers": "30",
    "convert_buildings": False,
    "buildings_default_height": "10.0",
    "buildings_workers": "4",
    "buildings_layer": "auto",
    "mode": "auto",
    "scale_mode": "target_size",
    "target_size_mm": "100",
    "target_resolution_mm": "0.3",
    "target_edge": "longest",
    "tile_size_mm": "",
    "scale_ratio": "",
    "step": "1",
    "grid_tolerance": "0.0",
    "z_scale": "1.0",
    "merge_out": "output/terrain.stl",
    "weld_tolerance": "0.01",
    "merge_z_scale": "1.0",
    "make_solid": True,
    "base_thickness": "5.0",
    "base_z": "",
    "base_mode": "fixed",
    "merge_border_mode": "all",
    "border_shp": "",
    "border_scale": "auto",
    "include_buildings": False,
    "status_idle": "",
}
