DEFAULTS = {
    "window_title": "SwissTopo STL Converter",
    "window_geometry": "900x700",
    "model_name": "terrain",
    "csv_path": "",
    "download_workers": "10",
    "convert_workers": "30",
    "mode": "auto",
    "target_size_mm": "100",
    "target_resolution_mm": "0.3",
    "target_edge": "longest",
    "step": "1",
    "grid_tolerance": "0.0",
    "z_scale": "1.0",
    "merge_out": "output/terrain.stl",
    "weld_tolerance": "0.01",
    "merge_z_scale": "1.0",
    "make_solid": True,
    "base_thickness": "5.0",
    "base_z": "",
    "base_mode": "fixed",
    "status_idle": "",
}
