name: swisstopo-stl
channels:
  - defaults
dependencies:
  - affine=2.4.0
  - attrs=25.4.0
  - blas=1.0
  - blosc=1.21.6
  - boost-cpp=1.82.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2026.01.04
  - cfitsio=3.470
  - click=8.1.8
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - expat=2.7.3
  - fiona=1.10.1
  - fontconfig=2.15.0
  - freetype=2.14.1
  - freexl=2.0.0
  - gdal=3.6.2
  - geos=3.10.6
  - geotiff=1.7.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - intel-openmp=2025.0.0
  - jpeg=9f
  - kealib=1.5.0
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libboost=1.82.0
  - libcurl=8.17.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgdal=3.6.2
  - libglib=2.84.2
  - libhwloc=2.12.1
  - libiconv=1.16
  - libkml=1.3.0
  - libkrb5=1.22.1
  - libnetcdf=4.8.1
  - libpng=1.6.54
  - libpq=17.4
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzip=1.8.0
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - minizip=4.0.3
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.19
  - pcre2=10.42
  - pip=25.3
  - pixman=0.46.4
  - poppler=24.09.0
  - poppler-data=0.4.12
  - proj=9.3.1
  - pyparsing=3.2.5
  - pyshp=3.0.2.post1
  - python=3.11.14
  - qhull=2020.2
  - rasterio=1.4.3
  - setuptools=80.9.0
  - shapely=2.1.2
  - sqlite=3.51.1
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tiledb=2.3.3
  - tk=8.6.15
  - tzdata=2025c
  - ucrt=10.0.22621.0
  - uriparser=0.9.8
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xerces-c=3.2.4
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - scipy==1.17.0
